FROM python:3.6 AS mosaik-orch-base

RUN apt-get update

### mosaik orchestrator base
RUN pip install --upgrade pip
RUN pip install mosaik~=2.6.0 mosaik-api~=2.4.2 simpy~=3.0.13 simpy.io~=0.2.3

WORKDIR /mosaik

ENV PYTHONDONTWRITEBYTECODE=1

FROM mosaik-orch-base

ARG SCENARIO_FILE
ARG EXTRA

### Add additional packages and simulators here.
### e.g.: RUN pip install mosaik-csv==1.0.3

COPY $SCENARIO_FILE .
COPY $EXTRA .
ENTRYPOINT python $SCENARIO_FILE
